In [11]:
#importig the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
#loading the dataset
df = pd.read_csv("titanic.csv")
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [13]:
#dropping the unecessary columns
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [14]:
#splitting the dataset into dependent and independent variables
inputs = df.drop('Survived',axis='columns')
target = df.Survived

In [15]:
#encoding categorical data
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

female  male
0       0     1
1       1     0
2       1     0

In [16]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

#### I am dropping male column as well because of dummy variable trap theory. One column is enough to repressent male vs female

In [17]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)
inputs.head(3)

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1

In [18]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [19]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [20]:
#replacing the null values with mean
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head()

Pclass   Age     Fare  female
0       3  22.0   7.2500       0
1       1  38.0  71.2833       1
2       3  26.0   7.9250       1
3       1  35.0  53.1000       1
4       3  35.0   8.0500       0

In [21]:
#splitting the dataset into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [22]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [23]:
model.fit(X_train,y_train)

GaussianNB()

In [24]:
#finding the accuracy
model.score(X_test,y_test)

0.7723880597014925

In [25]:
X_test[0:10]

Pclass        Age     Fare  female
45        3  29.699118   8.0500       0
701       1  35.000000  26.2875       0
205       3   2.000000  10.4625       1
848       2  28.000000  33.0000       0
427       2  19.000000  26.0000       1
801       2  31.000000  26.2500       1
448       3   5.000000  19.2583       1
99        2  34.000000  26.0000       0
227       3  20.500000   7.2500       0
285       3  33.000000   8.6625       0

In [26]:
y_test[0:10]

45     0
701    1
205    0
848    0
427    1
801    1
448    1
99     0
227    0
285    0
Name: Survived, dtype: int64

In [27]:
#finding the predicted values
model.predict(X_test[0:10])

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0], dtype=int64)

In [28]:
model.predict_proba(X_test[:10])

array([[0.97509677, 0.02490323],
       [0.77231347, 0.22768653],
       [0.26869308, 0.73130692],
       [0.93320424, 0.06679576],
       [0.24723763, 0.75276237],
       [0.28710524, 0.71289476],
       [0.30868651, 0.69131349],
       [0.94088315, 0.05911685],
       [0.97081048, 0.02918952],
       [0.97550785, 0.02449215]])

#### Calculate the score using cross validation

In [29]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.728     , 0.728     , 0.752     , 0.79032258, 0.74193548])